{
  pkgs,
  lib,
  ...
}: {
  home.activation.nushellInit = lib.hm.dag.entryAfter ["writeBoundary"] ''
    set -euo pipefail

    mkdir -p "$HOME/.config/nushell" "$HOME/.local/share/nushell/vendor/autoload"

    ${pkgs.starship}/bin/starship init nu > "$HOME/.local/share/nushell/vendor/autoload/starship.nu"
    ${pkgs.atuin}/bin/atuin init nu > "$HOME/.local/share/nushell/vendor/autoload/atuin.nu"
    ${pkgs.zoxide}/bin/zoxide init nushell > "$HOME/.local/share/nushell/vendor/autoload/zoxide.nu"
  '';

  xdg.configFile."nushell/env.nu".text = ''
    # Nushell environment config
    $env.TERM = "xterm-256color"

    def --env _path_prepend [p: string] {
      if not ($p | path exists) {
        return
      }

      let current = ($env.PATH? | default "")
      let parts = (if $current == "" { [] } else { $current | split row (char esep) })
      $env.PATH = ($parts | prepend $p | uniq | str join (char esep))
    }

    # Keep ~/.npm-global/bin early in PATH (Linux)
    ${lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
      _path_prepend ($env.HOME | path join ".npm-global" "bin")
      $env.NPM_CONFIG_PREFIX = ($env.HOME | path join ".npm-global")
    ''}

    # Basic Homebrew compatibility for Nushell (macOS)
    ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
      _path_prepend ($env.HOME | path join ".npm-global" "bin")
      $env.NPM_CONFIG_PREFIX = ($env.HOME | path join ".npm-global")

      _path_prepend "/opt/homebrew/sbin"
      _path_prepend "/opt/homebrew/bin"

      if ("/opt/homebrew" | path exists) {
        $env.HOMEBREW_PREFIX = "/opt/homebrew"
        $env.HOMEBREW_CELLAR = "/opt/homebrew/Cellar"
        $env.HOMEBREW_REPOSITORY = "/opt/homebrew"
      }
    ''}
  '';

  xdg.configFile."nushell/config.nu".text = ''
    # Nushell interactive config

    # Secrets are managed by sops-nix.
    ${lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
      const secrets = "~/.config/nushell/secrets.nu"
    ''}
    ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
      const secrets = "/run/secrets/rendered/nushell-secrets"
    ''}
    if ($secrets | path exists) {
      source-env $secrets
    }

    # Source bash-style env files (.env) into Nushell
    def --env envsource [file: path] {
      if not ($file | path exists) {
        error make { msg: $"envsource: file not found: ($file)" }
      }

      for l in (open $file | lines) {
        let line = ($l | str trim)
        if ($line == "" or ($line | str starts-with "#")) {
          continue
        }

        let cleaned = (
          if ($line | str starts-with "export ") {
            $line | str replace -r '^export[ \t]+' ""
          } else {
            $line
          }
        )

        let m = ($cleaned | parse -r '^(?P<key>[A-Za-z_][A-Za-z0-9_]*)=(?P<value>.*)$')
        if ($m | is-empty) {
          continue
        }

        let key = ($m.0.key | str trim)
        let raw = ($m.0.value | str trim | str replace -r ';$' "")
        let val = (
          $raw
          | str replace -r '^"(.*)"$' '$1'
          | str replace -r "^'(.*)'$" '$1'
        )

        load-env { ($key): $val }
      }

      print $"Sourced ($file)"
    }

    # Starship / Atuin / Zoxide are loaded via Nushell vendor autoload.
    # Files are generated by Home Manager activation into:
    #   ~/.local/share/nushell/vendor/autoload/{starship,atuin,zoxide}.nu

    # Aliases (kept intentionally separate from fish)
    alias g = git
    alias gs = git status
    alias ga = git add
    alias gc = git commit
    alias gp = git push
    alias gl = git log --oneline --graph
    alias ll = ls -la
    alias vim = nvim
    alias nv = nvim
    alias ff = fastfetch
    alias k = kubectl

    ${lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
      alias bjg = echo "I use NixOS, BTW"
    ''}

    def --env rebuild [] {
      ${lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
        cd ($env.HOME | path join ".config" "nix")
        sudo nixos-rebuild switch --flake .#thinker
      ''}
      ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
        cd ($env.HOME | path join ".config" "nix")
        sudo darwin-rebuild switch --flake .#Rivaldos-MacBook-Pro
      ''}
    }

    def --env update-flake [] {
      ${lib.optionalString pkgs.stdenv.hostPlatform.isLinux ''
        cd ($env.HOME | path join ".config" "nix")
        nix flake update
      ''}
      ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
        cd ($env.HOME | path join ".config" "nix")
        nix flake update
      ''}
    }
  '';
}
